#!/usr/bin/env bash
# Prep hive: sync deps and write ~/.config/hive/runtime.env
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="${HIVE_CONFIG_DIR:-$HOME/.config/hive}"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cd "$ROOT"

if command -v uv >/dev/null 2>&1; then
  uv sync --quiet
fi

RUNTIME="$CONFIG_DIR/runtime.env"
{
  echo "# generated by scripts/prep.sh — do not commit"
  echo "HIVE_PORT=8000"
  echo "HIVE_HOST=0.0.0.0"
  echo "HIVE_DATA_DIR=$ROOT/.hive"
  [ -n "${CURSOR_API_KEY:-}" ] && echo "CURSOR_API_KEY=$CURSOR_API_KEY"
  [ -n "${PRIME_API_KEY:-}" ] && echo "PRIME_API_KEY=$PRIME_API_KEY"
} >"$RUNTIME"
chmod 600 "$RUNTIME"

echo "[prep] wrote $RUNTIME"
