#!/usr/bin/env bash
# Prep radicle MCP: install rad CLI, npm deps, write runtime.env
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="${RADICLE_CONFIG_DIR:-$HOME/.config/radicle}"
MCP_DIR="$ROOT/mcp/radicle"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

export PATH="${HOME}/.radicle/bin:${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"

if ! command -v rad >/dev/null 2>&1; then
  echo "[prep] installing Radicle CLI ..."
  curl -fsSL https://radicle.xyz/install | sh -s -- --prefix="${RAD_HOME:-$HOME/.radicle}"
  export PATH="${HOME}/.radicle/bin:$PATH"
fi

if ! command -v node >/dev/null 2>&1; then
  echo "[prep] node not found — install Node.js 20+ on the VM" >&2
  exit 1
fi

cd "$MCP_DIR"
echo "[prep] npm install ..."
npm install --omit=dev

RUNTIME="$CONFIG_DIR/runtime.env"
{
  echo "# generated by scripts/prep.sh — do not commit"
  echo "RADICLE_MCP_PORT=${RADICLE_MCP_PORT:-8000}"
  echo "RADICLE_MCP_HOST=0.0.0.0"
  echo "RADICLE_MCP_ALLOWED_HOSTS=${RADICLE_MCP_ALLOWED_HOSTS:-radicle.boxd.sh,localhost}"
  echo "RAD_HOME=${RAD_HOME:-$HOME/.radicle}"
  echo "CURSOR_WORKSPACE=$ROOT"
  [ -n "${RAD_PASSPHRASE:-}" ] && echo "RAD_PASSPHRASE=$RAD_PASSPHRASE"
} >"$RUNTIME"
chmod 600 "$RUNTIME"

echo "[prep] wrote $RUNTIME"
echo "[prep] rad: $(rad --version 2>/dev/null | head -1 || echo missing)"
